<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contextmapper" nsURI="http://org/feature/context/mapper/model/contextmapper.ecore"
    nsPrefix="org.feature.context.mapper.model">
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraint" value="self.mapping &lt;> null"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" eType="ecore:EClass ../../org.feature.multi.perspective.mapping/model/viewmapping.ecore#//Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extend" upperBound="-1"
        eType="#//ExtendConnection" containment="true" eOpposite="#//ExtendConnection/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exclude" upperBound="-1"
        eType="#//ExcludeConnection" containment="true" eOpposite="#//ExcludeConnection/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excluded" upperBound="-1"
        eType="#//ExcludeConnection" eOpposite="#//ExcludeConnection/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priorize" upperBound="-1"
        eType="#//PriorConnection" containment="true" eOpposite="#//PriorConnection/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureClassification"
        eType="#//Classification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.featuremapper.models.feature/model/feature.ecore#//Feature"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Classification">
    <eLiterals name="dead"/>
    <eLiterals name="alive" value="1"/>
    <eLiterals name="unbound" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="include" upperBound="-1"
        eType="#//IncludeConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextDiagram">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraint" value="self.context->forAll(c1, c2  | c1.name&lt;>c2.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingReference" lowerBound="1"
        eType="ecore:EClass ../../org.feature.multi.perspective.mapping/model/viewmapping.ecore#//MappingModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" upperBound="-1"
        eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeconfig" upperBound="-1"
        eType="#//RuntimeConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Context" eOpposite="#//Context/extend"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcludeConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Context" resolveProxies="false" eOpposite="#//Context/exclude"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Context" resolveProxies="false" eOpposite="#//Context/excluded"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PriorConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Context" eOpposite="#//Context/priorize"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//RuntimeConfig"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Context"/>
  </eClassifiers>
</ecore:EPackage>
